--- Day 22: Monkey Market ---
As you're all teleported deep into the jungle, a monkey steals The Historians' device! You'll need to get it back while The Historians are looking for the Chief.

The monkey that stole the device seems willing to trade it, but only in exchange for an absurd number of bananas. Your only option is to buy bananas on the Monkey Exchange Market.

You aren't sure how the Monkey Exchange Market works, but one of The Historians senses trouble and comes over to help. Apparently, they've been studying these monkeys for a while and have deciphered their secrets.

Today, the Market is full of monkeys buying good hiding spots. Fortunately, because of the time you recently spent in this jungle, you know lots of good hiding spots you can sell! If you sell enough hiding spots, you should be able to get enough bananas to buy the device back.

On the Market, the buyers seem to use random prices, but their prices are actually only pseudorandom! If you know the secret of how they pick their prices, you can wait for the perfect time to sell.

The part about secrets is literal, the Historian explains. Each buyer produces a pseudorandom sequence of secret numbers where each secret is derived from the previous.

In particular, each buyer's secret number evolves into the next secret number in the sequence via the following process:

Calculate the result of multiplying the secret number by 64. Then, mix this result into the secret number. Finally, prune the secret number.
Calculate the result of dividing the secret number by 32. Round the result down to the nearest integer. Then, mix this result into the secret number. Finally, prune the secret number.
Calculate the result of multiplying the secret number by 2048. Then, mix this result into the secret number. Finally, prune the secret number.
Each step of the above process involves mixing and pruning:

To mix a value into the secret number, calculate the bitwise XOR of the given value and the secret number. Then, the secret number becomes the result of that operation. (If the secret number is 42 and you were to mix 15 into the secret number, the secret number would become 37.)
To prune the secret number, calculate the value of the secret number modulo 16777216. Then, the secret number becomes the result of that operation. (If the secret number is 100000000 and you were to prune the secret number, the secret number would become 16113920.)
After this process completes, the buyer is left with the next secret number in the sequence. The buyer can repeat this process as many times as necessary to produce more secret numbers.

So, if a buyer had a secret number of 123, that buyer's next ten secret numbers would be:

15887950
16495136
527345
704524
1553684
12683156
11100544
12249484
7753432
5908254
Each buyer uses their own secret number when choosing their price, so it's important to be able to predict the sequence of secret numbers for each buyer. Fortunately, the Historian's research has uncovered the initial secret number of each buyer (your puzzle input). For example:

1
10
100
2024
This list describes the initial secret number of four different secret-hiding-spot-buyers on the Monkey Exchange Market. If you can simulate secret numbers from each buyer, you'll be able to predict all of their future prices.

In a single day, buyers each have time to generate 2000 new secret numbers. In this example, for each buyer, their initial secret number and the 2000th new secret number they would generate are:

1: 8685429
10: 4700978
100: 15273692
2024: 8667524
Adding up the 2000th new secret number for each buyer produces 37327623.

For each buyer, simulate the creation of 2000 new secret numbers. What is the sum of the 2000th secret number generated by each buyer?

In [1]:
from math import log2
log2(64), log2(32), log2(2048), log2(16777216)

(6.0, 5.0, 11.0, 24.0)

In [2]:
with open("input22.txt") as file:
    data = [int(num) for num in file]
max(data) < 2 ** 24

True

In [3]:
"""
What are the operations?

First modification:
We add 6 0-bits (* 64)
We XOR the numbers (mix)
We retain the last 24 bits (prune)

Second modification:
We remove the last 5 bits (// 32)
We XOR the numbers (mix)
We retain the last 24 bits (prune)

Third modification:
Add 11 0-bits (* 2048)
We XOR the numbers (mix)
We retain the last 24 bits (prune)

So basically we work with 24 bit numbers (all puzzle input numbers are within 24 bits as well)

We bit-shift to the left or the right and calculate a XOR. This means that for multiplication with 2 ** x, the first and last x bits are retained, while the middle bits (24 - x) are mixed with an offset of x. However, after the prune we basically end with mixed bits + originals at the end

Multiplication (8-bit):
xxx12345678
xxx45678000

Floor division is the same thing from the other end, where the first X bits are retained, while the remaining bits are mixed with an offset of x

Floor division (8-bit):
    1234
12345678

What happens as we combine operations?
After the first modification, we have a 24bit number where the first 18 bits are mixed (as 1^7, 2^8 etc) and the final six bits are original again

The second modification retains the first 5 bits while mixing all others

The last modification retains the last 11 bits while mixing the others. 
"""

'\nWhat are the operations?\n\nFirst modification:\nWe add 6 0-bits (* 64)\nWe XOR the numbers (mix)\nWe retain the last 24 bits (prune)\n\nSecond modification:\nWe remove the last 5 bits (// 32)\nWe XOR the numbers (mix)\nWe retain the last 24 bits (prune)\n\nThird modification:\nAdd 11 0-bits (* 2048)\nWe XOR the numbers (mix)\nWe retain the last 24 bits (prune)\n\nSo basically we work with 24 bit numbers (all puzzle input numbers are within 24 bits as well)\n\nWe bit-shift to the left or the right and calculate a XOR. This means that for multiplication with 2 ** x, the first and last x bits are retained, while the middle bits (24 - x) are mixed with an offset of x. However, after the prune we basically end with mixed bits + originals at the end\n\nMultiplication (8-bit):\nxxx12345678\nxxx45678000\n\nFloor division is the same thing from the other end, where the first X bits are retained, while the remaining bits are mixed with an offset of x\n\nFloor division (8-bit):\n    1234\n12345678\n\nWhat happens as we combine operations?\nAfter the first modification, we have a 24bit number where the first 18 bits are mixed (as 1^7, 2^8 etc) and the final six bits are original again\n\nThe second modification retains the first 5 bits while mixing all others\n\nThe last modification retains the last 11 bits while mixing the others. \n'

In [4]:
# Let's create a little helper that allows us to see how each bit in the final secret number is computed:

bits = {x : [x] for x in range(24)}

def compose_full(ledger, pow2):
    # hard-code multiply/divide by power of two, mix and prune operations. Pow2 positive (for mult) or negative (for div)
    if pow2 > 0:
        for i in range(24 - pow2):
            ledger[i] += ledger[i + pow2]
    else:
        shift = -pow2
        for i in range(23, shift - 1, -1):
            ledger[i] += ledger[i - shift]
compose_full(bits, 6)
compose_full(bits, -5)
compose_full(bits, 11)
bits

{0: [0, 6, 11, 17, 6, 12],
 1: [1, 7, 12, 18, 7, 13],
 2: [2, 8, 13, 19, 8, 14],
 3: [3, 9, 14, 20, 9, 15],
 4: [4, 10, 15, 21, 10, 16],
 5: [5, 11, 0, 6, 16, 22, 11, 17],
 6: [6, 12, 1, 7, 17, 23, 12, 18],
 7: [7, 13, 2, 8, 18, 13, 19],
 8: [8, 14, 3, 9, 19, 14, 20],
 9: [9, 15, 4, 10, 20, 15, 21],
 10: [10, 16, 5, 11, 21, 16, 22],
 11: [11, 17, 6, 12, 22, 17, 23],
 12: [12, 18, 7, 13, 23, 18],
 13: [13, 19, 8, 14],
 14: [14, 20, 9, 15],
 15: [15, 21, 10, 16],
 16: [16, 22, 11, 17],
 17: [17, 23, 12, 18],
 18: [18, 13, 19],
 19: [19, 14, 20],
 20: [20, 15, 21],
 21: [21, 16, 22],
 22: [22, 17, 23],
 23: [23, 18]}

In [5]:
# Now for calculating the puzzle results, we can do this: We can automatically remove duplicate bits and then chain all 2000 secret number calculations to arrive at the final number
from functools import cache

def compose_lean(ledger, pow2):
    if pow2 > 0:
        for i in range(24 - pow2):
            ledger[i] ^= ledger[i + pow2]
    else:
        shift = -pow2
        for i in range(23, shift - 1, -1):
            ledger[i] ^= ledger[i - shift]

@cache
def compose_n(n):
    bits = {x : set([x]) for x in range(24)}
    for _ in range(n):
        compose_lean(bits, 6)
        compose_lean(bits, -5)
        compose_lean(bits, 11)
    return bits

secret_2000 = compose_n(2000)
secret_2000

{0: {2, 4, 5, 7, 10, 13, 14, 15, 16, 17, 23},
 1: {0, 1, 3, 4, 7, 9, 13, 15, 17, 18, 19, 21, 22},
 2: {0, 2, 5, 6, 10, 12, 16, 17, 19},
 3: {4, 5, 7, 8, 10, 11, 12, 13, 16, 17, 20, 21, 22},
 4: {0, 2, 5, 7, 9, 10, 12, 13, 16, 18, 19, 20, 22},
 5: {1, 2, 6, 9, 12, 13, 14, 15, 18, 19, 20, 21, 23},
 6: {0, 5, 9, 10, 11, 15, 17, 21, 22},
 7: {1, 2, 3, 7, 9, 13, 14, 19, 21, 22},
 8: {0, 3, 5, 7, 8, 9, 12, 13, 14, 15, 16, 18, 20, 21, 23},
 9: {5, 6, 7, 8, 15, 19},
 10: {1, 2, 3, 6, 7, 8, 9, 10, 12, 13, 16, 17, 18, 22},
 11: {0, 4, 5, 8, 10, 12, 13, 15, 17, 18, 22},
 12: {0, 2, 6, 8, 10, 11, 13, 14, 16, 19, 20, 21},
 13: {0, 3, 5, 6, 10, 11, 13, 14, 15, 17, 23},
 14: {1, 3, 5, 6, 7, 10, 11, 14, 15, 19, 21, 22, 23},
 15: {1, 3, 5, 9, 11, 13, 15, 19, 20, 23},
 16: {1, 2, 4, 10, 12, 18, 19},
 17: {0, 4, 9, 10, 11, 13, 14, 15, 17, 23},
 18: {3, 4, 5, 8, 11, 12, 14, 15, 17, 18, 22, 23},
 19: {5, 6, 7, 11, 13, 16, 17, 20, 23},
 20: {0, 2, 3, 5, 6, 10, 16, 17, 19},
 21: {0, 3, 6, 7, 9, 14, 16, 20, 21, 22, 23},
 22: {7, 8, 9, 14, 15, 16, 20},
 23: {0, 2, 3, 8, 9, 10, 13, 14, 15, 16, 18, 20, 21, 22, 23}}

In [6]:
def secret_num(seed, n):
    mapping = compose_n(n)
    seed_bits = [int(i) for i in f'{seed:024b}']
    bit_list = []
    for i in range(24):
        mapped_bit = sum([seed_bits[j] for j in mapping[i]]) % 2
        bit_list.append(mapped_bit)
    num = int(''.join(str(b) for b in bit_list), 2)
    return num
secret_num(2024, 2000)

8667524

In [7]:
sum_num = 0
for num in data:
    sum_num += secret_num(num, 2000)
sum_num

16039090236

Your puzzle answer was 16039090236.

The first half of this puzzle is complete! It provides one gold star: *

--- Part Two ---
Of course, the secret numbers aren't the prices each buyer is offering! That would be ridiculous. Instead, the prices the buyer offers are just the ones digit of each of their secret numbers.

So, if a buyer starts with a secret number of 123, that buyer's first ten prices would be:

3 (from 123)
0 (from 15887950)
6 (from 16495136)
5 (etc.)
4
4
6
4
4
2
This price is the number of bananas that buyer is offering in exchange for your information about a new hiding spot. However, you still don't speak monkey, so you can't negotiate with the buyers directly. The Historian speaks a little, but not enough to negotiate; instead, he can ask another monkey to negotiate on your behalf.

Unfortunately, the monkey only knows how to decide when to sell by looking at the changes in price. Specifically, the monkey will only look for a specific sequence of four consecutive changes in price, then immediately sell when it sees that sequence.

So, if a buyer starts with a secret number of 123, that buyer's first ten secret numbers, prices, and the associated changes would be:

     123: 3 
15887950: 0 (-3)
16495136: 6 (6)
  527345: 5 (-1)
  704524: 4 (-1)
 1553684: 4 (0)
12683156: 6 (2)
11100544: 4 (-2)
12249484: 4 (0)
 7753432: 2 (-2)
Note that the first price has no associated change because there was no previous price to compare it with.

In this short example, within just these first few prices, the highest price will be 6, so it would be nice to give the monkey instructions that would make it sell at that time. The first 6 occurs after only two changes, so there's no way to instruct the monkey to sell then, but the second 6 occurs after the changes -1,-1,0,2. So, if you gave the monkey that sequence of changes, it would wait until the first time it sees that sequence and then immediately sell your hiding spot information at the current price, winning you 6 bananas.

Each buyer only wants to buy one hiding spot, so after the hiding spot is sold, the monkey will move on to the next buyer. If the monkey never hears that sequence of price changes from a buyer, the monkey will never sell, and will instead just move on to the next buyer.

Worse, you can only give the monkey a single sequence of four price changes to look for. You can't change the sequence between buyers.

You're going to need as many bananas as possible, so you'll need to determine which sequence of four price changes will cause the monkey to get you the most bananas overall. Each buyer is going to generate 2000 secret numbers after their initial secret number, so, for each buyer, you'll have 2000 price changes in which your sequence can occur.

Suppose the initial secret number of each buyer is:

1
2
3
2024
There are many sequences of four price changes you could tell the monkey, but for these four buyers, the sequence that will get you the most bananas is -2,1,-1,3. Using that sequence, the monkey will make the following sales:

For the buyer with an initial secret number of 1, changes -2,1,-1,3 first occur when the price is 7.
For the buyer with initial secret 2, changes -2,1,-1,3 first occur when the price is 7.
For the buyer with initial secret 3, the change sequence -2,1,-1,3 does not occur in the first 2000 changes.
For the buyer starting with 2024, changes -2,1,-1,3 first occur when the price is 9.
So, by asking the monkey to sell the first time each buyer's prices go down 2, then up 1, then down 1, then up 3, you would get 23 (7 + 7 + 9) bananas!

Figure out the best sequence to tell the monkey so that by looking for that same sequence of changes in every buyer's future prices, you get the most bananas in total. What is the most bananas you can get?

In [8]:
"""
I was hoping my heavily optimized way of approaching calculating the n-th secret number would help me out in part 2. Alas, part 2 goes in a different direction. 

In fact, it might not be a bitwise problem at all (it might in subtle ways). On the surface, we have rolling sequences of single digit integer numbers and want to find a sequence of 4 (looking at the relative changes) that reliably leads to large final digits. Also note that a final digit of 0 to 7 corresponds to a 4 bit number, but an 8 or 9 corresponds to a 5 bit number!

In addition, if we look at the binary level, our XOR-maps show how numbers change between iterations, however it is a XOR pattern - it depends entirely on the initial seed if a particular sequence of XOR changes lead to a high or low final output. So my assumption is that the bit-wise level is not that significant here. 

"""

'\nI was hoping my heavily optimized way of approaching calculating the n-th secret number would help me out in part 2. Alas, part 2 goes in a different direction. \n\nIn fact, it might not be a bitwise problem at all (it might in subtle ways). On the surface, we have rolling sequences of single digit integer numbers and want to find a sequence of 4 (looking at the relative changes) that reliably leads to large final digits. Also note that a final digit of 0 to 7 corresponds to a 4 bit number, but an 8 or 9 corresponds to a 5 bit number!\n\nIn addition, if we look at the binary level, our XOR-maps show how numbers change between iterations, however it is a XOR pattern - it depends entirely on the initial seed if a particular sequence of XOR changes lead to a high or low final output. So my assumption is that the bit-wise level is not that significant here. \n\n'

In [9]:
def seq_prize(seed):
    seq = []
    sec = seed
    prize = sec % 10
    for _ in range(4):
        new_sec = secret_num(sec, 1)
        new_prize = new_sec % 10
        seq.append(new_prize - prize)
        sec, prize = new_sec, new_prize
    return (seq, prize)
seq_prize(16495136)

([-1, -1, 0, 2], 6)

In [12]:
"""
Let's generate random initial numbers and see if we can spot some trends
"""
from random import randint
def rand_seed():
    return secret_num(randint(0, 2**24 -1), 2) # wash it a bit for typicality

randoms = []
for _ in range(100000):
    randoms.append(seq_prize(rand_seed()))
len(randoms), randoms[:5]

(100000,
 [([1, 3, -5, 2], 5),
  ([-1, 2, -7, 1], 1),
  ([-5, 0, 2, 3], 9),
  ([7, -2, 1, -5], 3),
  ([1, -2, 4, 2], 9)])

In [13]:
import polars as pl
sample_data = {"prize" : [i[1] for i in randoms],
               "change_1" : [i[0][0] for i in randoms],
               "change_2" : [i[0][1] for i in randoms],
               "change_3" : [i[0][2] for i in randoms],
               "change_4" : [i[0][3] for i in randoms],}

sample_df = pl.DataFrame(sample_data)
sample_df.head()

shape: (5, 5)
┌───────┬──────────┬──────────┬──────────┬──────────┐
│ prize ┆ change_1 ┆ change_2 ┆ change_3 ┆ change_4 │
│ ---   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ i64   ┆ i64      ┆ i64      ┆ i64      ┆ i64      │
╞═══════╪══════════╪══════════╪══════════╪══════════╡
│ 5     ┆ 1        ┆ 3        ┆ -5       ┆ 2        │
│ 1     ┆ -1       ┆ 2        ┆ -7       ┆ 1        │
│ 9     ┆ -5       ┆ 0        ┆ 2        ┆ 3        │
│ 3     ┆ 7        ┆ -2       ┆ 1        ┆ -5       │
│ 9     ┆ 1        ┆ -2       ┆ 4        ┆ 2        │
└───────┴──────────┴──────────┴──────────┴──────────┘

In [14]:
sample_df.group_by('prize').len().sort('prize') # all prizes appear roughly equally often

shape: (10, 2)
┌───────┬───────┐
│ prize ┆ len   │
│ ---   ┆ ---   │
│ i64   ┆ u32   │
╞═══════╪═══════╡
│ 0     ┆ 10145 │
│ 1     ┆ 9997  │
│ 2     ┆ 9932  │
│ 3     ┆ 9924  │
│ 4     ┆ 9982  │
│ 5     ┆ 10083 │
│ 6     ┆ 10016 │
│ 7     ┆ 9947  │
│ 8     ┆ 9943  │
│ 9     ┆ 10031 │
└───────┴───────┘

In [15]:
pl.Config.set_tbl_rows(100)
sample_df.group_by('change_4').len().sort('change_4') # larger changes are rarer

shape: (19, 2)
┌──────────┬──────┐
│ change_4 ┆ len  │
│ ---      ┆ ---  │
│ i64      ┆ u32  │
╞══════════╪══════╡
│ -9       ┆ 1062 │
│ -8       ┆ 2029 │
│ -7       ┆ 3001 │
│ -6       ┆ 4088 │
│ -5       ┆ 5010 │
│ -4       ┆ 6031 │
│ -3       ┆ 7028 │
│ -2       ┆ 7838 │
│ -1       ┆ 9052 │
│ 0        ┆ 9974 │
│ 1        ┆ 8961 │
│ 2        ┆ 8105 │
│ 3        ┆ 7031 │
│ 4        ┆ 5752 │
│ 5        ┆ 5130 │
│ 6        ┆ 3930 │
│ 7        ┆ 2958 │
│ 8        ┆ 2049 │
│ 9        ┆ 971  │
└──────────┴──────┘

In [16]:
sample_df.filter(pl.col('prize') == 9).group_by('change_4').len().sort('change_4') # However, if we aim for a final prize of 9, the distribution is roughly equal

shape: (10, 2)
┌──────────┬──────┐
│ change_4 ┆ len  │
│ ---      ┆ ---  │
│ i64      ┆ u32  │
╞══════════╪══════╡
│ 0        ┆ 1021 │
│ 1        ┆ 961  │
│ 2        ┆ 1049 │
│ 3        ┆ 993  │
│ 4        ┆ 977  │
│ 5        ┆ 1064 │
│ 6        ┆ 1001 │
│ 7        ┆ 956  │
│ 8        ┆ 1038 │
│ 9        ┆ 971  │
└──────────┴──────┘

In [17]:
# sanity check: what if the final prize is 5?
sample_df.filter(pl.col('prize') == 5).group_by('change_4').len().sort('change_4')

shape: (10, 2)
┌──────────┬──────┐
│ change_4 ┆ len  │
│ ---      ┆ ---  │
│ i64      ┆ u32  │
╞══════════╪══════╡
│ -4       ┆ 1019 │
│ -3       ┆ 1043 │
│ -2       ┆ 981  │
│ -1       ┆ 1045 │
│ 0        ┆ 992  │
│ 1        ┆ 1019 │
│ 2        ┆ 1013 │
│ 3        ┆ 960  │
│ 4        ┆ 988  │
│ 5        ┆ 1023 │
└──────────┴──────┘

In [18]:
# Ok. Now what are the most common distributions ending in a 9?
df_nines = sample_df.filter(pl.col('prize') == 9)
df_nines.group_by(df_nines).len().sort('len', descending=True).head()

shape: (5, 6)
┌───────┬──────────┬──────────┬──────────┬──────────┬─────┐
│ prize ┆ change_1 ┆ change_2 ┆ change_3 ┆ change_4 ┆ len │
│ ---   ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ --- │
│ i64   ┆ i64      ┆ i64      ┆ i64      ┆ i64      ┆ u32 │
╞═══════╪══════════╪══════════╪══════════╪══════════╪═════╡
│ 9     ┆ -8       ┆ 3        ┆ 0        ┆ 5        ┆ 7   │
│ 9     ┆ 4        ┆ -7       ┆ 5        ┆ 3        ┆ 6   │
│ 9     ┆ 4        ┆ -2       ┆ -2       ┆ 5        ┆ 6   │
│ 9     ┆ 4        ┆ -5       ┆ 8        ┆ 0        ┆ 6   │
│ 9     ┆ 0        ┆ 0        ┆ 3        ┆ 1        ┆ 6   │
└───────┴──────────┴──────────┴──────────┴──────────┴─────┘

In [19]:
df_nines = df_nines.with_columns(start_prize = pl.col('prize') - pl.col('change_4') - pl.col('change_3') - pl.col('change_2') - pl.col('change_1'))
df_nines.group_by('start_prize').len().sort('start_prize')

shape: (10, 2)
┌─────────────┬──────┐
│ start_prize ┆ len  │
│ ---         ┆ ---  │
│ i64         ┆ u32  │
╞═════════════╪══════╡
│ 0           ┆ 970  │
│ 1           ┆ 970  │
│ 2           ┆ 984  │
│ 3           ┆ 997  │
│ 4           ┆ 995  │
│ 5           ┆ 1064 │
│ 6           ┆ 996  │
│ 7           ┆ 992  │
│ 8           ┆ 1007 │
│ 9           ┆ 1056 │
└─────────────┴──────┘

In [20]:
df_nines.filter(pl.col('start_prize') == 0).group_by(["change_1", "change_2", "change_3", "change_4"]).len().sort('len', descending=True).head(20)

shape: (20, 5)
┌──────────┬──────────┬──────────┬──────────┬─────┐
│ change_1 ┆ change_2 ┆ change_3 ┆ change_4 ┆ len │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆ --- │
│ i64      ┆ i64      ┆ i64      ┆ i64      ┆ u32 │
╞══════════╪══════════╪══════════╪══════════╪═════╡
│ 0        ┆ 1        ┆ 3        ┆ 5        ┆ 6   │
│ 5        ┆ -3       ┆ 7        ┆ 0        ┆ 5   │
│ 7        ┆ 1        ┆ -1       ┆ 2        ┆ 5   │
│ 0        ┆ 7        ┆ -6       ┆ 8        ┆ 5   │
│ 7        ┆ 2        ┆ -4       ┆ 4        ┆ 4   │
│ 0        ┆ 2        ┆ 0        ┆ 7        ┆ 4   │
│ 6        ┆ -1       ┆ 0        ┆ 4        ┆ 4   │
│ 4        ┆ 0        ┆ -1       ┆ 6        ┆ 4   │
│ 1        ┆ 6        ┆ -3       ┆ 5        ┆ 4   │
│ 5        ┆ 1        ┆ -1       ┆ 4        ┆ 4   │
│ 9        ┆ -9       ┆ 9        ┆ 0        ┆ 4   │
│ 5        ┆ 3        ┆ -5       ┆ 6        ┆ 3   │
│ 2        ┆ 7        ┆ -3       ┆ 3        ┆ 3   │
│ 7        ┆ -1       ┆ 3        ┆ 0        ┆ 3   │
│ 6        ┆ 1        ┆ -4       ┆ 6        ┆ 3   │
│ 1        ┆ 3        ┆ 0        ┆ 5        ┆ 3   │
│ 0        ┆ 2        ┆ 1        ┆ 6        ┆ 3   │
│ 4        ┆ -4       ┆ 8        ┆ 1        ┆ 3   │
│ 5        ┆ 0        ┆ -3       ┆ 7        ┆ 3   │
│ 9        ┆ -7       ┆ 3        ┆ 4        ┆ 3   │
└──────────┴──────────┴──────────┴──────────┴─────┘

In [21]:
"""
Well I don't think the statistical exploration has shown anything conclusive besides that it is a reasonable assumption that our final prize we aim for should be a 9 (the highest possible payoff) since all prizes are roughly equally common and that we should consider having a 0 prize somewhere in the sequence to guarantee that 9 payoff

Other than that, individual prizes seem to be mostly uncorrelated
"""

p_df = sample_df.with_columns(p3 = pl.col('prize') - pl.col('change_4'),
                                   p2 = pl.col('prize') - pl.col('change_4') - pl.col('change_3'),
                                   p1 = pl.col('prize') - pl.col('change_4') - pl.col('change_3') - pl.col('change_2'),
                                   p0 = pl.col('prize') - pl.col('change_4') - pl.col('change_3') - pl.col('change_2') - pl.col('change_1'))
p_df = p_df.select(['p0', 'p1', 'p2', 'p3', 'prize'])
p_df.corr()

shape: (5, 5)
┌──────────┬───────────┬───────────┬───────────┬───────────┐
│ p0       ┆ p1        ┆ p2        ┆ p3        ┆ prize     │
│ ---      ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64      ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.0      ┆ 0.003883  ┆ 0.000603  ┆ -0.00203  ┆ 0.000717  │
│ 0.003883 ┆ 1.0       ┆ -0.000877 ┆ -0.004526 ┆ -0.003255 │
│ 0.000603 ┆ -0.000877 ┆ 1.0       ┆ 0.001355  ┆ -0.002084 │
│ -0.00203 ┆ -0.004526 ┆ 0.001355  ┆ 1.0       ┆ -0.002562 │
│ 0.000717 ┆ -0.003255 ┆ -0.002084 ┆ -0.002562 ┆ 1.0       │
└──────────┴───────────┴───────────┴───────────┴───────────┘

In [105]:
# Ok let's go back to optimize a more bruteforce approach.
from copy import deepcopy
from collections import defaultdict

@cache
def compose_n(n):
    if n > 1:
        bits = deepcopy(compose_n(n-1))
    else:
        bits = {x : set([x]) for x in range(24)}
        if n == 0:
            return bits

    compose_lean(bits, 6)
    compose_lean(bits, -5)
    compose_lean(bits, 11)

    return bits

@cache
def bitmask_n(n):
    bit_masks = []
    for ix_out in range(24):
        num_str = ''
        for mask_bit in range(24):
            if mask_bit in compose_n(n)[ix_out]:
                num_str += '1'
            else:
                num_str += '0'
        bit_masks.append(int(num_str, 2))
    return bit_masks

def secret_num(seed, n):
    result = 0
    for i in range(24):
        bit = (seed & bitmask_n(n)[i]).bit_count() & 1
        result |= bit << 23 - i
    return result

def prize(seed, n):
    return secret_num(seed, n) % 10

def one_merchant(seed):
    prizes = [prize(seed, n) for n in range(2001)]
    changes = [p1 - p0 for p0, p1 in zip(prizes, prizes[1:])]
    ch_4 = [(changes[i-3], changes[i-2], changes[i-1], changes[i]) for i in range(3, len(changes))]
    seq_dict = {}
    for c,p in zip(ch_4, prizes[4:]):
        seq_dict.setdefault(c, p)

    return seq_dict

In [106]:
test_data = [1, 2, 3, 2024]

In [107]:
all_merchants = []
for merchant_seed in test_data:
    all_merchants.append(one_merchant(merchant_seed))

In [108]:
# iterate through sequences:
all_seq = set(seq for merchant in all_merchants for seq in merchant)
seq_ban = {}
for seq in all_seq:
    sum_ban = 0
    for merchant in all_merchants:
        sum_ban += merchant.setdefault(seq, 0)
    seq_ban[seq] = sum_ban

In [109]:
max(seq_ban, key=seq_ban.get)

(-2, 1, -1, 3)

In [110]:
seq_ban[(-2, 1, -1, 3)]

23

In [111]:
with open("input22.txt") as file:
    data = [int(num) for num in file]
all_merchants = []
for merchant_seed in data:
    all_merchants.append(one_merchant(merchant_seed))

In [ ]:
# iterate through sequences:
all_seq = set(seq for merchant in all_merchants for seq in merchant)
seq_ban = {}
for seq in all_seq:
    sum_ban = 0
    for merchant in all_merchants:
        sum_ban += merchant.get(seq, 0)
    seq_ban[seq] = sum_ban

In [113]:
max(seq_ban, key=seq_ban.get)

(-2, 3, -3, 3)

In [114]:
seq_ban[(-2, 3, -3, 3)]

1808

In [115]:
dict(sorted(seq_ban.items(), key=lambda x: x[1], reverse=True))

{(-2, 3, -3, 3): 1808,
 (0, 1, 0, 0): 1785,
 (-2, 2, -2, 2): 1726,
 (1, 1, 0, 0): 1723,
 (2, 0, -1, 2): 1719,
 (-2, 0, 1, 1): 1717,
 (0, 0, -1, 3): 1715,
 (0, -2, 1, 1): 1704,
 (2, -1, -1, 2): 1700,
 (-1, -1, 1, 1): 1700,
 (-1, -1, 1, 2): 1692,
 (-1, -1, 2, 0): 1672,
 (-1, 1, -1, 2): 1670,
 (1, 0, 0, 0): 1669,
 (-1, 0, 1, 0): 1665,
 (1, -1, 2, 0): 1661,
 (-1, -1, -1, 3): 1659,
 (0, -3, 1, 2): 1658,
 (3, -4, 1, 4): 1654,
 (1, -2, 1, 1): 1651,
 (-1, 0, 1, 1): 1649,
 (0, 0, 1, 2): 1646,
 (1, 0, -1, 1): 1644,
 (1, -1, -1, 2): 1644,
 (0, -2, 0, 3): 1639,
 (-1, 1, 2, 0): 1637,
 (0, 2, 0, 1): 1636,
 (0, -3, 3, 1): 1636,
 (-1, -2, 2, 2): 1632,
 (-2, 3, -1, 1): 1631,
 (-1, 2, 0, 0): 1630,
 (-2, 2, 0, 1): 1628,
 (0, -1, 1, 1): 1626,
 (0, 4, -3, 3): 1626,
 (1, -1, 1, 3): 1624,
 (-1, 2, -2, 2): 1624,
 (-1, 1, -1, 1): 1623,
 (-1, 0, 0, 2): 1620,
 (0, 1, 1, 0): 1620,
 (-1, 2, -2, 3): 1619,
 (0, 0, 0, 1): 1619,
 (1, 0, 0, 1): 1618,
 (0, 0, -1, 1): 1616,
 (0, 1, -1, 1): 1614,
 (1, 1, -4, 4): 1613,
 (-3, 0, -1, 4): 1613,
 (0, -4, 1, 3): 1612,
 (0, 0, 2, 2): 1611,
 (0, 0, 1, 0): 1610,
 (2, 0, -1, 1): 1610,
 (1, -1, 1, 1): 1609,
 (-4, 4, -1, 1): 1608,
 (0, 2, -2, 2): 1606,
 (0, -4, 3, 1): 1606,
 (0, -2, 0, 2): 1605,
 (-1, 1, 0, 2): 1604,
 (-1, 1, 1, 0): 1603,
 (2, -3, 2, 2): 1602,
 (3, 0, 0, 0): 1602,
 (0, -1, 0, 1): 1600,
 (0, -1, 1, 2): 1595,
 (-4, 2, -1, 3): 1594,
 (1, 0, -2, 2): 1593,
 (-3, 1, 1, 1): 1591,
 (-2, 1, 0, 2): 1590,
 (-4, 2, 2, 0): 1589,
 (1, -1, 1, 0): 1588,
 (4, -4, 0, 4): 1588,
 (0, 0, -2, 2): 1587,
 (0, -2, 3, 0): 1585,
 (2, 1, 0, 0): 1584,
 (-4, 4, -3, 3): 1584,
 (0, 0, 1, 1): 1580,
 (-1, 1, 0, 0): 1578,
 (0, 0, 3, 0): 1578,
 (-1, 0, 0, 1): 1578,
 (0, 0, 0, 0): 1574,
 (-3, 2, 1, 1): 1573,
 (-2, 0, 3, 0): 1572,
 (0, -4, 4, 0): 1571,
 (-4, 4, -2, 2): 1570,
 (-2, 1, 3, 0): 1568,
 (1, 0, -2, 3): 1567,
 (-2, 0, 0, 2): 1566,
 (2, 1, -3, 3): 1566,
 (1, -1, 1, 2): 1564,
 (1, 0, -4, 4): 1564,
 (0, 1, 1, 1): 1563,
 (0, -2, 1, 2): 1562,
 (1, 1, -3, 3): 1562,
 (1, -4, 1, 3): 1559,
 (0, 0, 0, 2): 1558,
 (0, 1, -3, 3): 1558,
 (3, -1, 0, 2): 1558,
 (-3, 0, 0, 3): 1557,
 (-2, 0, 1, 3): 1555,
 (0, -1, 0, 2): 1553,
 (-1, 1, 0, 1): 1553,
 (-2, 4, -3, 3): 1552,
 (2, 2, 0, 0): 1551,
 (1, -2, -1, 3): 1551,
 (-2, 3, 0, 0): 1548,
 (-1, -3, 1, 3): 1547,
 (-4, 1, 1, 2): 1547,
 (1, 0, -3, 3): 1546,
 (2, -1, 1, 0): 1545,
 (-1, 1, 1, 1): 1545,
 (-2, -2, 3, 1): 1543,
 (0, -1, 2, 1): 1543,
 (-2, -1, 4, 0): 1540,
 (-3, 2, -2, 3): 1540,
 (-3, 2, -3, 4): 1539,
 (0, 0, 1, 3): 1539,
 (0, -3, 2, 1): 1538,
 (-4, 1, 0, 4): 1537,
 (1, 2, -2, 3): 1537,
 (0, -1, 2, 0): 1536,
 (-1, -1, 3, 1): 1536,
 (0, -1, -1, 2): 1535,
 (-3, 3, -2, 3): 1535,
 (-2, 2, -2, 3): 1535,
 (1, -1, -1, 3): 1535,
 (0, -1, -2, 3): 1532,
 (3, -3, 2, 2): 1532,
 (-1, 2, -1, 1): 1531,
 (4, -4, 5, 0): 1531,
 (2, 0, 0, 1): 1530,
 (1, -1, 3, 0): 1529,
 (-1, 1, -3, 3): 1529,
 (2, 0, 1, 0): 1528,
 (-1, 0, 2, 0): 1526,
 (3, -3, 3, 0): 1524,
 (1, -2, 0, 3): 1524,
 (2, -2, 2, 0): 1523,
 (1, 0, 2, 0): 1522,
 (1, 3, -4, 4): 1521,
 (-2, 0, 2, 0): 1521,
 (-2, 0, 1, 2): 1521,
 (-3, 2, -1, 2): 1520,
 (-1, -1, 1, 3): 1519,
 (-3, 2, 0, 1): 1519,
 (-2, -1, 0, 3): 1518,
 (1, 1, 2, 0): 1517,
 (-4, 2, 1, 1): 1516,
 (-1, -2, 3, 0): 1515,
 (0, 2, -1, 2): 1515,
 (2, 0, 0, 0): 1511,
 (-1, 0, -2, 3): 1511,
 (-2, 0, -2, 4): 1510,
 (-3, 3, -1, 1): 1509,
 (-2, 2, -1, 2): 1509,
 (-1, -1, 2, 1): 1507,
 (4, 0, -2, 2): 1507,
 (1, 1, -1, 1): 1506,
 (0, -3, 3, 0): 1506,
 (-4, 5, -4, 4): 1505,
 (1, 3, -1, 2): 1504,
 (-1, 1, 1, 2): 1504,
 (-3, 1, 3, 0): 1503,
 (2, 3, -1, 1): 1503,
 (0, -3, 0, 3): 1501,
 (1, -3, 1, 3): 1501,
 (-1, 1, -2, 3): 1501,
 (-1, 3, -3, 3): 1499,
 (-1, 0, 3, 1): 1499,
 (0, 4, 0, 0): 1499,
 (1, -4, 2, 2): 1499,
 (0, -1, -1, 3): 1498,
 (2, -2, 0, 2): 1497,
 (-4, 3, -2, 3): 1496,
 (0, 3, 0, 0): 1495,
 (-1, 0, -1, 2): 1494,
 (1, 0, -2, 4): 1493,
 (2, -2, 0, 3): 1492,
 (1, -2, 2, 3): 1492,
 (-1, 0, 2, 2): 1492,
 (1, -2, 1, 2): 1491,
 (5, -5, 4, 1): 1491,
 (-2, 1, -1, 2): 1491,
 (-1, 3, -4, 4): 1491,
 (3, 0, -2, 2): 1491,
 (-3, -1, 4, 0): 1491,
 (0, 1, -2, 2): 1491,
 (1, -5, 1, 4): 1490,
 (-3, 3, -2, 2): 1490,
 (0, 0, -2, 3): 1489,
 (-2, 2, -1, 1): 1488,
 (0, -1, 0, 3): 1488,
 (1, -1, 0, 3): 1487,
 (-3, 1, -1, 4): 1486,
 (0, 2, 1, 0): 1485,
 (2, -1, 0, 1): 1485,
 (-1, 0, 0, 3): 1484,
 (0, 2, -2, 3): 1484,
 (4, -1, -1, 2): 1484,
 (1, 2, -3, 4): 1483,
 (-3, 0, 1, 2): 1482,
 (-3, 3, -4, 4): 1482,
 (1, -2, 3, 1): 1482,
 (0, 2, 0, 0): 1481,
 (0, 0, -2, 4): 1481,
 (1, -3, -1, 5): 1480,
 (1, 1, 1, 0): 1480,
 (1, -4, 4, 0): 1480,
 (1, 0, -1, 3): 1480,
 (4, 1, 0, 0): 1480,
 (0, 2, -1, 1): 1480,
 (-1, 0, -3, 4): 1479,
 (2, -4, 3, 2): 1478,
 (2, -2, 3, 1): 1478,
 (1, -3, 3, 1): 1478,
 (3, -3, 1, 3): 1478,
 (1, -3, 2, 2): 1477,
 (2, -2, 1, 3): 1477,
 (2, 0, -2, 4): 1476,
 (-2, 1, -1, 3): 1475,
 (4, -3, 1, 3): 1475,
 (-2, 1, 0, 1): 1475,
 (1, -1, 0, 1): 1474,
 (2, 2, -1, 1): 1473,
 (-1, 1, -1, 0): 1473,
 (1, 0, -1, 2): 1473,
 (2, -3, 0, 3): 1473,
 (1, 0, -3, 4): 1472,
 (-2, 0, 1, 4): 1472,
 (4, -3, 1, 2): 1470,
 (2, 1, -1, 2): 1468,
 (-3, 4, -1, 1): 1467,
 (0, -3, -1, 4): 1465,
 (0, -2, 2, 0): 1465,
 (-4, 1, 3, 1): 1465,
 (-1, -2, 2, 1): 1465,
 (-1, 0, 1, 2): 1465,
 (1, -1, -2, 4): 1464,
 (4, 0, 0, 0): 1463,
 (-4, 3, 0, 1): 1463,
 (1, -3, -1, 4): 1463,
 (1, -3, 1, 2): 1462,
 (0, 3, -3, 3): 1462,
 (3, -1, 1, 0): 1462,
 (2, -1, -1, 3): 1460,
 (1, -3, 2, 1): 1460,
 (0, -1, 3, 0): 1460,
 (2, -1, 0, 3): 1459,
 (2, -1, 2, 0): 1459,
 (-2, 1, 0, 3): 1458,
 (-2, 1, -3, 4): 1457,
 (3, 0, -1, 1): 1457,
 (3, -3, 2, 1): 1457,
 (-1, -3, 3, 2): 1457,
 (-1, 0, 3, 0): 1456,
 (3, -1, 2, 0): 1456,
 (2, -2, 3, 0): 1456,
 (0, 1, -1, 3): 1454,
 (0, 0, 2, 1): 1454,
 (-1, 3, -5, 5): 1454,
 (-1, 3, -1, 2): 1453,
 (-2, 2, 0, 0): 1453,
 (2, -1, 2, 1): 1452,
 (-2, 3, -2, 3): 1452,
 (1, 2, 1, 0): 1452,
 (-1, -1, 0, 2): 1451,
 (1, 0, -2, 1): 1451,
 (-2, 1, 1, 0): 1450,
 (1, -3, 0, 4): 1450,
 (3, 1, -3, 3): 1450,
 (2, -3, 3, 0): 1450,
 (-1, 3, 0, 1): 1447,
 (-2, 1, 1, 1): 1447,
 (2, 1, -3, 4): 1447,
 (-1, -1, 3, 2): 1446,
 (-1, 2, 1, 0): 1446,
 (-2, -2, 0, 4): 1446,
 (-1, -2, 0, 3): 1444,
 (-1, 2, 0, 1): 1443,
 (0, -2, 0, 4): 1443,
 (3, -2, 2, 1): 1443,
 (4, -4, 1, 3): 1443,
 (-2, 0, -1, 3): 1443,
 (2, -4, 2, 2): 1442,
 (-4, -1, 2, 3): 1442,
 (4, -2, -2, 4): 1442,
 (-4, 1, 3, 0): 1442,
 (-3, 1, 0, 2): 1441,
 (1, 4, -1, 0): 1441,
 (4, -1, 0, 1): 1441,
 (-4, 3, 0, 2): 1441,
 (-4, 3, -1, 2): 1441,
 (2, -1, 1, 2): 1441,
 (1, -4, 5, 0): 1440,
 (-4, 2, -2, 4): 1440,
 (0, 3, -2, 2): 1440,
 (0, 1, 0, 1): 1440,
 (-2, 3, -2, 2): 1440,
 (4, -1, 1, 0): 1440,
 (-1, -3, 1, 4): 1439,
 (-1, 1, -1, 3): 1439,
 (0, -1, -2, 4): 1438,
 (1, 3, -3, 3): 1437,
 (-3, -1, 1, 4): 1437,
 (3, -1, -1, 3): 1437,
 (-5, 1, 1, 3): 1437,
 (-3, 0, 2, 1): 1437,
 (4, 0, -3, 3): 1436,
 (-1, -3, 3, 1): 1436,
 (1, -2, 2, 0): 1436,
 (0, 0, 0, 5): 1436,
 (2, -3, 2, 3): 1434,
 (-1, 1, -2, 2): 1433,
 (2, 0, -2, 3): 1433,
 (2, 0, -1, 3): 1433,
 (-2, 3, -4, 4): 1433,
 (-2, 0, 2, 1): 1433,
 (1, 0, 1, 1): 1433,
 (3, -1, 0, 1): 1432,
 (1, 1, -1, 3): 1432,
 (0, 1, -3, 4): 1432,
 (0, -1, 2, 2): 1431,
 (1, -3, 3, 0): 1430,
 (1, 1, -3, 5): 1430,
 (-2, 2, 1, 1): 1430,
 (3, -3, 0, 4): 1429,
 (1, 1, -1, 2): 1429,
 (0, 1, -1, 2): 1429,
 (0, 1, 0, 4): 1428,
 (-2, -2, 5, 0): 1428,
 (-2, 0, 4, 0): 1427,
 (2, -1, 1, 1): 1427,
 (0, -2, 2, 1): 1427,
 (-1, 2, 0, 3): 1427,
 (1, 1, -3, 4): 1425,
 (2, 3, -5, 5): 1425,
 (1, 0, 1, 0): 1425,
 (-4, 0, 1, 3): 1425,
 (0, 1, -2, 3): 1424,
 (-2, 0, 3, 2): 1424,
 (1, 0, 3, 0): 1424,
 (0, -1, 3, 3): 1424,
 (2, 0, 2, 0): 1424,
 (1, -1, 0, 4): 1424,
 (-2, -2, 4, 0): 1423,
 (-2, 0, 2, 3): 1423,
 (-3, 0, 1, 4): 1423,
 (-2, 1, 1, 2): 1423,
 (-2, 3, 1, 0): 1422,
 (-4, 4, -1, 2): 1422,
 (0, 0, -4, 4): 1422,
 (0, 1, 2, 0): 1421,
 (1, 0, 0, 2): 1421,
 (3, -4, 1, 3): 1421,
 (-1, -2, -1, 4): 1420,
 (-3, 1, 1, 2): 1419,
 (-1, 2, -1, 2): 1419,
 (0, 4, -4, 4): 1418,
 (2, -3, 1, 4): 1418,
 (-3, 3, -3, 3): 1417,
 (3, -2, 1, 3): 1417,
 (1, 3, 1, 0): 1417,
 (-2, 1, -1, 1): 1417,
 (-1, -1, -3, 5): 1416,
 (3, -2, 0, 4): 1416,
 (0, 1, 0, 2): 1416,
 (3, -1, -2, 4): 1416,
 (2, -1, -1, 4): 1414,
 (-1, 1, 2, 1): 1414,
 (3, -5, 5, 0): 1414,
 (-1, 3, 1, 1): 1414,
 (0, -1, 1, 0): 1413,
 (1, 2, -2, 2): 1413,
 (3, 1, -2, 3): 1412,
 (-3, 3, 1, 0): 1412,
 (3, -2, 0, 2): 1412,
 (2, -3, 3, 1): 1411,
 (3, 0, 1, 0): 1411,
 (3, 1, -1, 1): 1411,
 (4, -2, 3, 0): 1411,
 (-1, 5, -5, 5): 1411,
 (3, -3, 1, 2): 1410,
 (3, 1, -2, 2): 1409,
 (1, -1, -3, 4): 1408,
 (2, -2, 0, 4): 1408,
 (-1, 3, -2, 3): 1408,
 (0, -2, 2, 2): 1408,
 (2, -2, -1, 3): 1407,
 (-2, 0, 3, 1): 1407,
 (3, 2, -2, 2): 1407,
 (-3, 2, -1, 4): 1407,
 (0, 1, 4, 0): 1407,
 (-2, 3, -3, 4): 1406,
 (4, -2, 1, 1): 1406,
 (-3, 2, -2, 4): 1405,
 (1, 2, -1, 3): 1405,
 (-1, 3, 0, 0): 1404,
 (0, 0, 2, 0): 1404,
 (-4, 4, 0, 0): 1404,
 (4, -4, 2, 2): 1404,
 (1, -5, 5, 0): 1403,
 (-1, 1, -1, 6): 1403,
 (-4, 1, -1, 4): 1402,
 (0, -4, 2, 1): 1402,
 (-2, -1, 2, 1): 1402,
 (3, -2, 4, 0): 1402,
 (1, 1, -2, 3): 1402,
 (1, 3, -2, 2): 1402,
 (-1, -1, 3, 0): 1401,
 (1, -2, 0, 2): 1401,
 (2, -3, 1, 2): 1401,
 (-2, 1, -1, 5): 1401,
 (-1, 2, -2, 4): 1401,
 (-4, 0, 3, 1): 1400,
 (1, -2, 3, -1): 1400,
 (-1, -4, 0, 5): 1399,
 (-4, 6, -1, 1): 1399,
 (0, 1, 3, 0): 1399,
 (1, 1, -1, 5): 1398,
 (3, -1, -2, 3): 1398,
 (-1, 3, -1, 1): 1397,
 (-1, 3, -1, 3): 1397,
 (-1, -3, 2, 2): 1397,
 (2, 0, 1, 2): 1397,
 (1, -2, 0, 4): 1397,
 (3, -3, -1, 4): 1397,
 (1, -1, -1, 4): 1396,
 (-1, -4, 5, 0): 1395,
 (-1, -2, 1, 2): 1395,
 (-5, 3, 0, 2): 1394,
 (1, 3, 0, 0): 1394,
 (-3, 2, -4, 5): 1394,
 (-1, 4, -4, 3): 1394,
 (0, 3, -1, 1): 1393,
 (1, -1, -2, 3): 1393,
 (1, -4, 0, 4): 1393,
 (1, 1, -4, 5): 1393,
 (3, -2, 2, 0): 1392,
 (-2, -1, 3, 0): 1392,
 (-1, -2, 4, 0): 1392,
 (0, 3, -3, 4): 1392,
 (1, 1, 1, 2): 1392,
 (2, -3, 0, 5): 1392,
 (4, -3, 3, 1): 1392,
 (0, 1, 0, 3): 1392,
 (5, -5, 1, 4): 1391,
 (0, -2, -1, 3): 1391,
 (0, 3, 0, 1): 1391,
 (-1, -1, -1, 4): 1391,
 (3, 0, -2, 3): 1391,
 (2, 1, 0, 1): 1391,
 (-1, 4, 0, 0): 1391,
 (2, -2, 2, 1): 1390,
 (3, -4, 0, 4): 1390,
 (1, -2, 2, 1): 1390,
 (-1, 3, -2, 4): 1390,
 (-3, 1, 0, 3): 1389,
 (-1, 3, -2, 2): 1389,
 (-3, 2, -1, 3): 1389,
 (0, 3, -3, 5): 1387,
 (1, 2, -4, 4): 1387,
 (4, 0, -1, 1): 1387,
 (1, -4, 3, 1): 1387,
 (0, 2, -3, 3): 1387,
 (-3, 0, -1, 5): 1386,
 (-4, 3, -2, 4): 1386,
 (4, -3, 2, 1): 1386,
 (-1, 0, -1, 4): 1385,
 (-1, -1, -1, 2): 1385,
 (1, 2, 2, 0): 1385,
 (0, -3, 1, 3): 1385,
 (0, 2, -3, 2): 1384,
 (-2, 2, -3, 3): 1383,
 (-1, 0, 4, 0): 1383,
 (0, -2, 4, 0): 1383,
 (-2, 0, 5, 0): 1382,
 (2, -3, 2, 1): 1382,
 (2, -1, -2, 3): 1382,
 (4, -4, 4, 1): 1382,
 (-1, -3, 0, 4): 1382,
 (1, -1, 5, 1): 1382,
 (-2, 2, -2, 4): 1382,
 (0, -1, -2, 2): 1381,
 (2, 2, -4, 4): 1381,
 (0, 3, -4, 5): 1381,
 (3, -4, 4, 0): 1381,
 (1, -3, 4, 1): 1380,
 (-2, -2, 1, 3): 1380,
 (1, -1, 2, 1): 1379,
 (-2, 4, 0, 0): 1379,
 (2, -5, 1, 4): 1379,
 (3, 1, -1, 2): 1378,
 (-1, 4, 0, 1): 1378,
 (-3, 3, 2, 0): 1378,
 (0, 3, -5, 5): 1378,
 (-2, 1, 1, -1): 1378,
 (-2, 0, 0, 3): 1377,
 (-1, 4, -2, 2): 1377,
 (-2, 0, 0, 1): 1377,
 (4, 0, 1, 0): 1376,
 (1, -1, 4, 0): 1376,
 (-3, 4, -2, 2): 1376,
 (5, -4, 2, 2): 1376,
 (2, -1, 0, 2): 1376,
 (1, 0, 2, -1): 1375,
 (-1, 1, 0, -1): 1375,
 (0, -4, 2, 2): 1375,
 (-1, -2, 5, 0): 1375,
 (1, 1, -2, 4): 1373,
 (-1, 4, -1, 1): 1373,
 (-5, 2, 2, 1): 1373,
 (-4, -1, 0, 5): 1373,
 (-4, 2, 0, 3): 1372,
 (0, -1, -1, 4): 1371,
 (3, -1, -3, 4): 1371,
 (-1, 0, 2, 1): 1370,
 (4, -4, 2, 3): 1369,
 (-2, 1, 2, 0): 1369,
 (0, 0, -3, 3): 1369,
 (-1, 1, 2, 2): 1369,
 (-1, -4, 1, 4): 1368,
 (3, -1, 1, 1): 1368,
 (0, -4, 0, 5): 1368,
 (-5, 1, 4, 0): 1368,
 (2, -3, -1, 4): 1368,
 (-2, 3, 1, 1): 1368,
 (0, -1, 1, 3): 1367,
 (-2, -1, 4, 1): 1367,
 (0, -1, 0, 5): 1367,
 (1, -1, -2, 5): 1366,
 (0, 2, 2, 0): 1366,
 (2, -4, 4, 0): 1365,
 (2, -2, 2, 2): 1365,
 (3, -2, 1, 2): 1365,
 (4, -4, 4, 0): 1364,
 (2, -2, 3, 2): 1364,
 (0, 4, 0, 1): 1364,
 (3, 1, 0, 0): 1364,
 (-2, 0, 2, 2): 1364,
 (-1, -1, 0, 1): 1363,
 (1, 1, 0, 2): 1363,
 (1, 2, -1, 1): 1363,
 (-3, -1, 3, 1): 1363,
 (1, -3, 3, 2): 1363,
 (4, -4, 1, 4): 1363,
 (0, -3, 2, 4): 1363,
 (-5, 3, 1, 1): 1363,
 (0, -1, -3, 4): 1363,
 (-4, 1, 0, 3): 1362,
 (5, -3, -2, 5): 1362,
 (3, -4, 2, 2): 1362,
 (-4, 4, -2, 3): 1362,
 (2, 1, 0, 2): 1361,
 (2, 1, -1, 1): 1361,
 (-1, 2, -2, 5): 1361,
 (0, 3, -1, 3): 1361,
 (-3, 3, 0, 0): 1361,
 (0, 2, 1, 1): 1361,
 (0, -3, 1, 4): 1361,
 (-1, 4, -2, 3): 1360,
 (0, 1, -3, 5): 1360,
 (-1, 2, 0, 2): 1360,
 (-2, 4, -4, 6): 1360,
 (-3, 0, 4, 0): 1360,
 (-2, 1, 1, 3): 1359,
 (-1, 1, -4, 5): 1359,
 (-2, -1, 2, 3): 1359,
 (-1, -5, 4, 2): 1359,
 (-2, 4, -1, 1): 1359,
 (3, -3, 3, -1): 1359,
 (0, 0, -3, 4): 1359,
 (4, -2, 0, 2): 1358,
 (0, -1, 3, 1): 1357,
 (0, -2, 3, 1): 1357,
 (-5, 1, -1, 5): 1356,
 (2, 0, -3, 3): 1356,
 (1, -2, 0, 5): 1355,
 (3, -1, -1, 2): 1355,
 (0, 0, 4, 1): 1355,
 (-2, 2, -4, 4): 1355,
 (-3, 1, 2, 0): 1355,
 (-1, 5, -5, 4): 1355,
 (0, 5, -5, 5): 1355,
 (0, 1, 1, 2): 1355,
 (5, 0, -3, 3): 1355,
 (0, 0, -1, 2): 1355,
 (3, -2, 0, 3): 1354,
 (0, 0, 1, 4): 1354,
 (-4, -1, 1, 4): 1354,
 (3, 0, 0, 1): 1354,
 (-3, 2, 1, 2): 1353,
 (2, -1, 0, 4): 1353,
 (0, -3, 0, 4): 1353,
 (-2, -1, 3, 1): 1353,
 (0, 2, -1, 3): 1353,
 (-2, -1, 1, 1): 1353,
 (-2, 2, -1, 4): 1353,
 (4, -1, -3, 4): 1352,
 (3, 0, -3, 3): 1352,
 (2, -2, 1, 2): 1352,
 (0, 2, 0, 2): 1352,
 (-1, -1, -2, 4): 1352,
 (3, 0, -3, 5): 1351,
 (-5, 0, 3, 2): 1351,
 (2, 1, -2, 3): 1351,
 (2, 0, 0, 2): 1351,
 (1, -3, 0, 2): 1350,
 (-3, 0, 0, 4): 1350,
 (2, -5, 4, 1): 1350,
 (-6, 2, 1, 3): 1349,
 (0, 2, -4, 4): 1349,
 (2, -4, 5, 0): 1349,
 (0, -4, 5, 0): 1349,
 (5, -5, 3, 3): 1349,
 (-1, 1, -5, 5): 1349,
 (0, -1, 2, -1): 1349,
 (2, 0, -2, 2): 1349,
 (3, -3, 0, 3): 1348,
 (1, -4, -1, 6): 1348,
 (2, -2, 4, 0): 1348,
 (-3, 2, 1, 0): 1347,
 (-4, 1, 2, 1): 1347,
 (4, -4, 3, 1): 1347,
 (2, -2, -1, 5): 1347,
 (2, -3, 4, 1): 1347,
 (-4, 0, 4, 0): 1346,
 (5, -2, -1, 3): 1346,
 (-3, 1, -1, 3): 1345,
 (-3, 3, 0, 1): 1345,
 (1, -2, 1, 3): 1344,
 (2, 1, -2, 2): 1344,
 (1, 2, -1, 2): 1343,
 (-2, 1, 2, 1): 1343,
 (-4, -1, 3, 2): 1343,
 (3, -1, 3, 0): 1342,
 (1, -2, -1, 5): 1342,
 (1, 0, 2, 1): 1342,
 (0, 3, 0, 2): 1342,
 (1, -2, 3, 0): 1341,
 (5, -3, 2, 1): 1341,
 (1, 1, 1, -1): 1341,
 (2, 2, -3, 3): 1341,
 (-2, 2, 2, 0): 1341,
 (3, -2, -1, 5): 1341,
 (-4, 4, 1, 0): 1341,
 (0, -1, 4, 0): 1341,
 (2, 3, -4, 4): 1340,
 (2, -1, -2, 5): 1340,
 (-4, 1, 1, 3): 1339,
 (-2, -1, 0, 5): 1338,
 (0, 3, -1, 2): 1338,
 (3, 2, 0, 0): 1338,
 (-1, 3, 1, 0): 1338,
 (1, 1, 2, 1): 1338,
 (-2, 1, -2, 4): 1338,
 (1, 1, 1, 1): 1337,
 (-4, 3, -3, 4): 1337,
 (1, 0, -3, 2): 1337,
 (-3, 5, 0, 0): 1337,
 (0, -5, 1, 4): 1337,
 (-1, 2, -3, 3): 1336,
 (-1, 0, -1, 5): 1336,
 (1, -2, 1, 0): 1336,
 (-1, 1, 0, 3): 1336,
 (4, -1, 1, 1): 1336,
 (0, -2, -1, 2): 1335,
 (0, 2, -3, 5): 1335,
 (0, -3, -1, 5): 1335,
 (-2, 2, 0, 2): 1335,
 (1, -1, 3, -1): 1335,
 (2, -2, 4, 1): 1335,
 (3, 1, -4, 4): 1335,
 (-2, 0, -1, 4): 1334,
 (1, -2, -1, 4): 1334,
 (1, 1, -2, 1): 1334,
 (2, -3, 4, -1): 1333,
 (-2, 2, 1, 0): 1333,
 (1, -2, 1, 5): 1333,
 (-2, 3, -2, 4): 1333,
 (-3, -1, 2, 2): 1332,
 (-4, 4, -4, 4): 1332,
 (-1, 1, -1, 4): 1332,
 (2, -1, 3, 1): 1331,
 (2, 3, -3, 3): 1331,
 (-1, 0, -1, 3): 1331,
 (2, -3, 2, 0): 1331,
 (0, 4, -2, 2): 1330,
 (1, -1, 0, 2): 1330,
 (3, -2, -1, 4): 1330,
 (2, 0, -3, 2): 1330,
 (-1, -1, 4, 0): 1329,
 (2, 2, -2, 2): 1329,
 (1, 2, 0, 2): 1329,
 (2, -3, 1, 1): 1329,
 (0, -3, 5, 0): 1329,
 (1, -1, 0, 0): 1329,
 (1, 1, 0, 1): 1328,
 (0, -3, 4, 0): 1328,
 (4, -4, 0, 5): 1328,
 (4, 0, -3, 4): 1327,
 (-1, 2, -3, 4): 1327,
 (-3, 0, 1, 3): 1327,
 (5, 0, 0, 1): 1327,
 (-1, 2, -1, 3): 1327,
 (0, 2, -5, 5): 1327,
 (1, 2, 0, 1): 1327,
 (1, 4, -5, 5): 1326,
 (-3, 3, -3, 4): 1326,
 (-4, 0, 2, 3): 1325,
 (0, 3, -2, 3): 1325,
 (1, -1, -2, 2): 1325,
 (2, -1, -1, 1): 1325,
 (-1, -3, 4, 1): 1325,
 (-3, 1, -2, 5): 1324,
 (-2, 3, -1, 2): 1324,
 (2, -4, 1, 3): 1324,
 (1, -3, 2, 3): 1324,
 (-1, -1, 2, 2): 1324,
 (-2, 3, -4, 3): 1323,
 (-1, 1, 3, 0): 1323,
 (-1, -1, 4, 1): 1323,
 (1, 0, 0, 3): 1323,
 (1, 2, -3, 3): 1322,
 (5, -4, 4, 0): 1322,
 (-1, 3, 0, -1): 1321,
 (-1, 4, 1, 0): 1321,
 (-3, -2, 3, 2): 1321,
 (-3, 5, -5, 5): 1321,
 (-3, -2, 5, 0): 1321,
 (3, -2, 1, 1): 1320,
 (-1, -2, 2, 3): 1320,
 (-2, 0, -1, 2): 1320,
 (2, -4, 1, 4): 1320,
 (-1, 1, -4, 4): 1319,
 (1, 0, 0, -1): 1319,
 (1, -3, 4, -1): 1319,
 (1, 1, -2, 2): 1319,
 (-1, 3, 2, 0): 1319,
 (5, -2, -2, 4): 1319,
 (-2, -1, -1, 4): 1319,
 (0, -1, 1, -1): 1319,
 (1, 1, -1, 4): 1318,
 (0, -3, -2, 5): 1318,
 (1, 0, -4, 5): 1318,
 (0, -3, 3, 2): 1317,
 (0, -5, 0, 5): 1317,
 (0, -4, 3, 2): 1317,
 (3, -1, 2, -1): 1317,
 (0, -4, 3, 0): 1317,
 (3, -1, -2, 5): 1317,
 (2, -4, 3, 1): 1317,
 (3, -2, -1, 2): 1316,
 (2, -5, 3, 2): 1316,
 (2, -2, 2, 3): 1316,
 (-4, 5, -2, 2): 1316,
 (-2, 3, -1, 0): 1316,
 (1, 0, 4, 0): 1315,
 (0, -4, 4, -1): 1315,
 (4, -2, 2, 0): 1315,
 (3, 1, -2, 1): 1315,
 (4, 1, -3, 2): 1315,
 (3, -3, 3, 1): 1314,
 (3, 2, -3, 3): 1314,
 (1, 4, -4, 4): 1314,
 (-3, 2, -2, 2): 1313,
 (-3, 3, -1, 2): 1313,
 (0, -2, 3, 2): 1313,
 (1, 2, 0, 0): 1313,
 (3, 1, 0, 1): 1313,
 (-1, 0, 1, 3): 1312,
 (2, 2, 0, 1): 1312,
 (0, 1, -4, 4): 1312,
 (2, -2, -2, 5): 1312,
 (-1, 2, 0, -1): 1311,
 (-1, 0, 0, 4): 1311,
 (4, 1, -2, 2): 1311,
 (-2, -2, 0, 5): 1310,
 (-3, 0, 5, 0): 1310,
 (2, 0, -3, 4): 1310,
 (1, 0, -5, 5): 1310,
 (-2, 0, 0, 4): 1310,
 (0, 2, -2, 4): 1309,
 (1, 3, -1, 1): 1309,
 (-5, 0, 2, 2): 1309,
 (-3, 1, 4, -1): 1308,
 (2, 0, -2, 5): 1308,
 (-1, -2, 1, 3): 1307,
 (-2, 3, -2, 1): 1307,
 (4, -4, -1, 5): 1307,
 (-3, 4, -4, 4): 1307,
 (-3, 1, 2, 1): 1307,
 (0, 4, -3, 4): 1306,
 (0, -1, 0, 4): 1306,
 (-1, 2, 1, 1): 1306,
 (-1, -2, 0, 5): 1305,
 (-4, 3, 0, 0): 1305,
 (-2, -3, 4, 1): 1305,
 (2, -2, 0, 5): 1304,
 (3, -2, -2, 5): 1304,
 (2, -3, 1, 3): 1303,
 (-3, 0, -2, 5): 1303,
 (3, -2, -1, 3): 1303,
 (0, 1, 2, 1): 1303,
 (2, -1, 1, -1): 1303,
 (-1, 1, -2, 1): 1303,
 (-3, 2, 0, 2): 1302,
 (-2, 4, -4, 4): 1302,
 (-1, 4, -3, 4): 1302,
 (2, -3, 4, 0): 1302,
 (-1, 3, -4, 5): 1302,
 (0, 1, 2, 2): 1302,
 (0, -4, 1, 4): 1302,
 (-1, 0, -2, 4): 1301,
 (-2, 5, -4, 4): 1301,
 (5, -4, 4, -1): 1301,
 (0, 3, 1, 0): 1301,
 (4, 1, -6, 6): 1301,
 (3, -3, 0, 5): 1301,
 (1, -2, 4, 0): 1300,
 (3, -2, 0, 1): 1300,
 (-4, 3, 1, 0): 1300,
 (2, -4, 0, 4): 1300,
 (-2, 2, -3, 4): 1299,
 (0, 0, 3, -1): 1299,
 (3, -2, 2, 2): 1299,
 (0, -3, -1, 6): 1299,
 (-1, -1, 0, 4): 1299,
 (-3, 4, -3, 3): 1299,
 (0, -2, 2, 3): 1299,
 (1, -4, 2, 3): 1298,
 (2, -5, 0, 5): 1298,
 (1, -2, -2, 4): 1298,
 (5, -1, -2, 3): 1298,
 (-3, 5, -4, 4): 1298,
 (-3, 0, 3, 1): 1298,
 (-3, 0, 2, 2): 1298,
 (-4, 3, 2, 1): 1298,
 (-2, 2, 1, 2): 1297,
 (3, -4, 4, -1): 1297,
 (0, 2, -2, 1): 1297,
 (-2, 1, -2, 3): 1296,
 (-3, -1, 0, 4): 1296,
 (-2, 0, 4, 1): 1296,
 (-4, 1, 2, 0): 1296,
 (3, 0, 1, 1): 1296,
 (2, 0, -4, 3): 1296,
 (-5, 5, -4, 5): 1296,
 (0, -1, 5, 0): 1296,
 (-2, 4, -4, 3): 1296,
 (-1, 1, -1, 5): 1296,
 (-1, -4, 4, 1): 1295,
 (3, 0, 0, -1): 1295,
 (1, -1, -3, 5): 1295,
 (2, -2, -2, 4): 1295,
 (2, 1, 1, 1): 1295,
 (5, -4, 1, 3): 1295,
 (3, -5, 2, 3): 1295,
 (-4, 1, 0, 2): 1294,
 (-4, 0, 2, 2): 1294,
 (0, -1, 2, 3): 1294,
 (0, 1, -4, 5): 1293,
 (1, -4, 3, 0): 1293,
 (0, -2, -2, 5): 1293,
 (1, 3, -3, 2): 1293,
 (1, -3, 3, 3): 1293,
 (-4, 3, -1, 3): 1292,
 (-1, -2, 0, 2): 1292,
 (3, 0, 2, 0): 1292,
 (-3, 4, -5, 4): 1292,
 (0, -2, -1, 4): 1292,
 (0, 0, 1, -1): 1292,
 (-1, 3, -1, 0): 1292,
 (-1, 0, 0, 5): 1292,
 (2, -1, 1, 3): 1292,
 (-2, -2, -1, 5): 1291,
 (-1, 0, 2, 3): 1291,
 (-1, 2, -4, 4): 1291,
 (3, 1, 1, 0): 1291,
 (1, -2, -2, 5): 1291,
 (0, 0, -1, 4): 1291,
 (2, 0, -1, 0): 1291,
 (-1, -3, 2, 3): 1291,
 (2, 0, 0, 3): 1291,
 (0, 5, -2, 2): 1290,
 (-3, 0, 3, 0): 1290,
 (1, -1, 1, 4): 1290,
 (3, -5, 0, 5): 1290,
 (2, -5, 5, 0): 1289,
 (0, -3, 0, 5): 1289,
 (1, -1, 3, 2): 1289,
 (-5, 5, -2, 3): 1289,
 (3, 0, -1, 0): 1289,
 (1, -2, 2, 2): 1288,
 (-5, 2, -2, 5): 1288,
 (2, 2, 2, 0): 1288,
 (-1, -2, 3, 1): 1288,
 (4, -1, 0, 2): 1288,
 (-2, 5, 0, 0): 1288,
 (0, 0, 3, 1): 1287,
 (-4, 2, 3, 1): 1287,
 (-3, 1, -1, 5): 1286,
 (-2, 5, 0, 1): 1286,
 (2, 1, -3, 2): 1286,

That's the right answer! You are one gold star closer to finding the Chief Historian.

You have completed Day 22! You can [Share] this victory or [Return to Your Advent Calendar].
I love my baby bubu and my baby babu